const jobActionTypes = {
    FETCH_ALL_JOBS_START:'FETCH_ALL_JOBS_START',
    SUCCESS:'SUCCESS',
    FAILED:'FAILED',
    UPDATE_JOB_START:'UPDATE_JOB_START',
    DELETE_JOB_START:'DELETE_JOB_START',
    CREATE_JOB_START:'CREATE_JOB_START'
}

export default jobActionTypes;