const postActionTypes = {
    FETCH_ALL_POSTS_START:'FETCH_ALL_POSTS_START',
    SUCCESS:'POST_SUCCESS',
    FAILED:'POST_FAILED',
    UPDATE_POST_START:'UPDATE_POST_START',
    DELETE_POST_START:'DELETE_POST_START',
    CREATE_POST_START:'CREATE_POST_START'
}

export default postActionTypes;