const userActionTypes = {
    SIGN_IN_START: 'SIGN_IN_START',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT: 'SIGN_OUT',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    EDIT_DETAILS_START:'EDIT_DETAILS_START',
    EDIT_DETAILS_SUCCESS:'EDIT_DETAILS_SUCCESS',
    EDIT_DETAILS_FAILURE:'EDIT_DETAILS_FAILURE',
    FETCH_USER:'FETCH_USER'
}

export default userActionTypes;